[package]
name = "rust_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
kafka_wire_protocol = { path = "../rust" }
testcontainers = { version = "0.22.0", features = ["blocking"] }
byteorder = "1.5.0"
