// This file was generated. Do not edit.

use std::io::{Read, Result, Write};

use serde::{Deserialize, Serialize};
#[cfg(test)] use proptest_derive::Arbitrary;

use crate::arrays::{read_array, read_nullable_array, write_array, write_nullable_array};
use crate::markers::{ApiMessage, Response};
use crate::readable_writable::{Readable, Writable};
use crate::tagged_fields::{RawTaggedField, read_tagged_fields, write_tagged_fields};
#[cfg(test)] use crate::test_utils::proptest_strategies;

/// StreamsGroupHeartbeatResponse, version 0.
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
#[cfg_attr(test, derive(Arbitrary))]
pub struct StreamsGroupHeartbeatResponse {
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,
    /// The top-level error code, or 0 if there was no error
    pub error_code: i16,
    /// The top-level error message, or null if there was no error.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::optional_string()"))]
    pub error_message: Option<String>,
    /// The member id is always generated by the streams consumer.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::string()"))]
    pub member_id: String,
    /// The member epoch.
    pub member_epoch: i32,
    /// The heartbeat interval in milliseconds.
    pub heartbeat_interval_ms: i32,
    /// The maximal lag a warm-up task can have to be considered caught-up.
    pub acceptable_recovery_lag: i32,
    /// The interval in which the task changelog offsets on a client are updated on the broker. The offsets are sent with the next heartbeat after this time has passed.
    pub task_offset_interval_ms: i32,
    /// Indicate zero or more status for the group.  Null if unchanged since last heartbeat.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::optional_vec()"))]
    pub status: Option<Vec<Status>>,
    /// Assigned active tasks for this client. Null if unchanged since last heartbeat.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::optional_vec()"))]
    pub active_tasks: Option<Vec<TaskIds>>,
    /// Assigned standby tasks for this client. Null if unchanged since last heartbeat.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::optional_vec()"))]
    pub standby_tasks: Option<Vec<TaskIds>>,
    /// Assigned warm-up tasks for this client. Null if unchanged since last heartbeat.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::optional_vec()"))]
    pub warmup_tasks: Option<Vec<TaskIds>>,
    /// The endpoint epoch set in the response
    pub endpoint_information_epoch: i32,
    /// Global assignment information used for IQ. Null if unchanged since last heartbeat.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::optional_vec()"))]
    pub partitions_by_user_endpoint: Option<Vec<EndpointToPartitions>>,
    /// Unknown tagged fields.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::unknown_tagged_fields()"))]
    pub _unknown_tagged_fields: Vec<RawTaggedField>,
}

impl ApiMessage for StreamsGroupHeartbeatResponse {
    fn api_key(&self) -> i16 {
        88
    }
    
    fn version(&self) -> i16 {
        0
    }
}

impl Response for StreamsGroupHeartbeatResponse { }

impl Default for StreamsGroupHeartbeatResponse {
    fn default() -> Self {
        StreamsGroupHeartbeatResponse {
            throttle_time_ms: 0_i32,
            error_code: 0_i16,
            error_message: None,
            member_id: String::from(""),
            member_epoch: 0_i32,
            heartbeat_interval_ms: 0_i32,
            acceptable_recovery_lag: 0_i32,
            task_offset_interval_ms: 0_i32,
            status: None,
            active_tasks: None,
            standby_tasks: None,
            warmup_tasks: None,
            endpoint_information_epoch: 0_i32,
            partitions_by_user_endpoint: None,
            _unknown_tagged_fields: Vec::new(),
        }
    }
}

impl StreamsGroupHeartbeatResponse {
    pub fn new<S1: AsRef<str>, S2: AsRef<str>>(throttle_time_ms: i32, error_code: i16, error_message: Option<S1>, member_id: S2, member_epoch: i32, heartbeat_interval_ms: i32, acceptable_recovery_lag: i32, task_offset_interval_ms: i32, status: Option<Vec<Status>>, active_tasks: Option<Vec<TaskIds>>, standby_tasks: Option<Vec<TaskIds>>, warmup_tasks: Option<Vec<TaskIds>>, endpoint_information_epoch: i32, partitions_by_user_endpoint: Option<Vec<EndpointToPartitions>>) -> Self {
        Self {
            throttle_time_ms,
            error_code,
            error_message: error_message.map(|s| s.as_ref().to_string()),
            member_id: member_id.as_ref().to_string(),
            member_epoch,
            heartbeat_interval_ms,
            acceptable_recovery_lag,
            task_offset_interval_ms,
            status,
            active_tasks,
            standby_tasks,
            warmup_tasks,
            endpoint_information_epoch,
            partitions_by_user_endpoint,
            _unknown_tagged_fields: vec![],
        }
    }
}

#[cfg(test)]
mod tests_streams_group_heartbeat_response_new_and_default {
    use super::*;
    
    #[test]
    fn test() {
        let d = StreamsGroupHeartbeatResponse::new(
            0_i32,
            0_i16,
            None::<String>,
            String::from(""),
            0_i32,
            0_i32,
            0_i32,
            0_i32,
            None::<Vec::<Status>>,
            None::<Vec::<TaskIds>>,
            None::<Vec::<TaskIds>>,
            None::<Vec::<TaskIds>>,
            0_i32,
            None::<Vec::<EndpointToPartitions>>,
        );
        assert_eq!(d, StreamsGroupHeartbeatResponse::default());
    }
}

impl Readable for StreamsGroupHeartbeatResponse {
    fn read(#[allow(unused)] input: &mut impl Read) -> Result<Self> {
        let throttle_time_ms = i32::read(input)?;
        let error_code = i16::read(input)?;
        let error_message = Option::<String>::read_ext(input, "error_message", true)?;
        let member_id = String::read_ext(input, "member_id", true)?;
        let member_epoch = i32::read(input)?;
        let heartbeat_interval_ms = i32::read(input)?;
        let acceptable_recovery_lag = i32::read(input)?;
        let task_offset_interval_ms = i32::read(input)?;
        let status = read_nullable_array::<Status>(input, "status", true)?;
        let active_tasks = read_nullable_array::<TaskIds>(input, "active_tasks", true)?;
        let standby_tasks = read_nullable_array::<TaskIds>(input, "standby_tasks", true)?;
        let warmup_tasks = read_nullable_array::<TaskIds>(input, "warmup_tasks", true)?;
        let endpoint_information_epoch = i32::read(input)?;
        let partitions_by_user_endpoint = read_nullable_array::<EndpointToPartitions>(input, "partitions_by_user_endpoint", true)?;
        let tagged_fields_callback = |tag: i32, _: &[u8]| {
            match tag {
                _ => Ok(false)
            }
        };
        let _unknown_tagged_fields = read_tagged_fields(input, tagged_fields_callback)?;
        Ok(StreamsGroupHeartbeatResponse {
            throttle_time_ms, error_code, error_message, member_id, member_epoch, heartbeat_interval_ms, acceptable_recovery_lag, task_offset_interval_ms, status, active_tasks, standby_tasks, warmup_tasks, endpoint_information_epoch, partitions_by_user_endpoint, _unknown_tagged_fields
        })
    }
}

impl Writable for StreamsGroupHeartbeatResponse {
    fn write(&self, #[allow(unused)] output: &mut impl Write) -> Result<()> {
        self.throttle_time_ms.write(output)?;
        self.error_code.write(output)?;
        self.error_message.write_ext(output, "self.error_message", true)?;
        self.member_id.write_ext(output, "self.member_id", true)?;
        self.member_epoch.write(output)?;
        self.heartbeat_interval_ms.write(output)?;
        self.acceptable_recovery_lag.write(output)?;
        self.task_offset_interval_ms.write(output)?;
        write_nullable_array(output, "self.status", self.status.as_deref(), true)?;
        write_nullable_array(output, "self.active_tasks", self.active_tasks.as_deref(), true)?;
        write_nullable_array(output, "self.standby_tasks", self.standby_tasks.as_deref(), true)?;
        write_nullable_array(output, "self.warmup_tasks", self.warmup_tasks.as_deref(), true)?;
        self.endpoint_information_epoch.write(output)?;
        write_nullable_array(output, "self.partitions_by_user_endpoint", self.partitions_by_user_endpoint.as_deref(), true)?;
        write_tagged_fields(output, &[], &self._unknown_tagged_fields)?;
        Ok(())
    }
}

/// EndpointToPartitions, version 0.
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
#[cfg_attr(test, derive(Arbitrary))]
pub struct EndpointToPartitions {
    /// User-defined endpoint to connect to the node
    pub user_endpoint: Endpoint,
    /// All topic partitions materialized by active tasks on the node
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::vec()"))]
    pub active_partitions: Vec<TopicPartition>,
    /// All topic partitions materialized by standby tasks on the node
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::vec()"))]
    pub standby_partitions: Vec<TopicPartition>,
    /// Unknown tagged fields.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::unknown_tagged_fields()"))]
    pub _unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for EndpointToPartitions {
    fn default() -> Self {
        EndpointToPartitions {
            user_endpoint: Endpoint::default(),
            active_partitions: Vec::<TopicPartition>::new(),
            standby_partitions: Vec::<TopicPartition>::new(),
            _unknown_tagged_fields: Vec::new(),
        }
    }
}

impl EndpointToPartitions {
    pub fn new(user_endpoint: Endpoint, active_partitions: Vec<TopicPartition>, standby_partitions: Vec<TopicPartition>) -> Self {
        Self {
            user_endpoint,
            active_partitions,
            standby_partitions,
            _unknown_tagged_fields: vec![],
        }
    }
}

#[cfg(test)]
mod tests_endpoint_to_partitions_new_and_default {
    use super::*;
    
    #[test]
    fn test() {
        let d = EndpointToPartitions::new(
            Endpoint::default(),
            Vec::<TopicPartition>::new(),
            Vec::<TopicPartition>::new(),
        );
        assert_eq!(d, EndpointToPartitions::default());
    }
}

impl Readable for EndpointToPartitions {
    fn read(#[allow(unused)] input: &mut impl Read) -> Result<Self> {
        let user_endpoint = Endpoint::read(input)?;
        let active_partitions = read_array::<TopicPartition>(input, "active_partitions", true)?;
        let standby_partitions = read_array::<TopicPartition>(input, "standby_partitions", true)?;
        let tagged_fields_callback = |tag: i32, _: &[u8]| {
            match tag {
                _ => Ok(false)
            }
        };
        let _unknown_tagged_fields = read_tagged_fields(input, tagged_fields_callback)?;
        Ok(EndpointToPartitions {
            user_endpoint, active_partitions, standby_partitions, _unknown_tagged_fields
        })
    }
}

impl Writable for EndpointToPartitions {
    fn write(&self, #[allow(unused)] output: &mut impl Write) -> Result<()> {
        self.user_endpoint.write(output)?;
        write_array(output, "self.active_partitions", &self.active_partitions, true)?;
        write_array(output, "self.standby_partitions", &self.standby_partitions, true)?;
        write_tagged_fields(output, &[], &self._unknown_tagged_fields)?;
        Ok(())
    }
}

/// Endpoint, version 0.
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
#[cfg_attr(test, derive(Arbitrary))]
pub struct Endpoint {
    /// host of the endpoint
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::string()"))]
    pub host: String,
    /// port of the endpoint
    pub port: u16,
    /// Unknown tagged fields.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::unknown_tagged_fields()"))]
    pub _unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for Endpoint {
    fn default() -> Self {
        Endpoint {
            host: String::from(""),
            port: 0_u16,
            _unknown_tagged_fields: Vec::new(),
        }
    }
}

impl Endpoint {
    pub fn new<S1: AsRef<str>>(host: S1, port: u16) -> Self {
        Self {
            host: host.as_ref().to_string(),
            port,
            _unknown_tagged_fields: vec![],
        }
    }
}

#[cfg(test)]
mod tests_endpoint_new_and_default {
    use super::*;
    
    #[test]
    fn test() {
        let d = Endpoint::new(
            String::from(""),
            0_u16,
        );
        assert_eq!(d, Endpoint::default());
    }
}

impl Readable for Endpoint {
    fn read(#[allow(unused)] input: &mut impl Read) -> Result<Self> {
        let host = String::read_ext(input, "host", true)?;
        let port = u16::read(input)?;
        let tagged_fields_callback = |tag: i32, _: &[u8]| {
            match tag {
                _ => Ok(false)
            }
        };
        let _unknown_tagged_fields = read_tagged_fields(input, tagged_fields_callback)?;
        Ok(Endpoint {
            host, port, _unknown_tagged_fields
        })
    }
}

impl Writable for Endpoint {
    fn write(&self, #[allow(unused)] output: &mut impl Write) -> Result<()> {
        self.host.write_ext(output, "self.host", true)?;
        self.port.write(output)?;
        write_tagged_fields(output, &[], &self._unknown_tagged_fields)?;
        Ok(())
    }
}

/// Status, version 0.
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
#[cfg_attr(test, derive(Arbitrary))]
pub struct Status {
    /// A code to indicate that a particular status is active for the group membership
    pub status_code: i8,
    /// A string representation of the status.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::string()"))]
    pub status_detail: String,
    /// Unknown tagged fields.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::unknown_tagged_fields()"))]
    pub _unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for Status {
    fn default() -> Self {
        Status {
            status_code: 0_i8,
            status_detail: String::from(""),
            _unknown_tagged_fields: Vec::new(),
        }
    }
}

impl Status {
    pub fn new<S1: AsRef<str>>(status_code: i8, status_detail: S1) -> Self {
        Self {
            status_code,
            status_detail: status_detail.as_ref().to_string(),
            _unknown_tagged_fields: vec![],
        }
    }
}

#[cfg(test)]
mod tests_status_new_and_default {
    use super::*;
    
    #[test]
    fn test() {
        let d = Status::new(
            0_i8,
            String::from(""),
        );
        assert_eq!(d, Status::default());
    }
}

impl Readable for Status {
    fn read(#[allow(unused)] input: &mut impl Read) -> Result<Self> {
        let status_code = i8::read(input)?;
        let status_detail = String::read_ext(input, "status_detail", true)?;
        let tagged_fields_callback = |tag: i32, _: &[u8]| {
            match tag {
                _ => Ok(false)
            }
        };
        let _unknown_tagged_fields = read_tagged_fields(input, tagged_fields_callback)?;
        Ok(Status {
            status_code, status_detail, _unknown_tagged_fields
        })
    }
}

impl Writable for Status {
    fn write(&self, #[allow(unused)] output: &mut impl Write) -> Result<()> {
        self.status_code.write(output)?;
        self.status_detail.write_ext(output, "self.status_detail", true)?;
        write_tagged_fields(output, &[], &self._unknown_tagged_fields)?;
        Ok(())
    }
}

/// TaskIds, version 0.
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
#[cfg_attr(test, derive(Arbitrary))]
pub struct TaskIds {
    /// The subtopology identifier.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::string()"))]
    pub subtopology_id: String,
    /// The partitions of the input topics processed by this member.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::vec()"))]
    pub partitions: Vec<i32>,
    /// Unknown tagged fields.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::unknown_tagged_fields()"))]
    pub _unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for TaskIds {
    fn default() -> Self {
        TaskIds {
            subtopology_id: String::from(""),
            partitions: Vec::<i32>::new(),
            _unknown_tagged_fields: Vec::new(),
        }
    }
}

impl TaskIds {
    pub fn new<S1: AsRef<str>>(subtopology_id: S1, partitions: Vec<i32>) -> Self {
        Self {
            subtopology_id: subtopology_id.as_ref().to_string(),
            partitions,
            _unknown_tagged_fields: vec![],
        }
    }
}

#[cfg(test)]
mod tests_task_ids_new_and_default {
    use super::*;
    
    #[test]
    fn test() {
        let d = TaskIds::new(
            String::from(""),
            Vec::<i32>::new(),
        );
        assert_eq!(d, TaskIds::default());
    }
}

impl Readable for TaskIds {
    fn read(#[allow(unused)] input: &mut impl Read) -> Result<Self> {
        let subtopology_id = String::read_ext(input, "subtopology_id", true)?;
        let partitions = read_array::<i32>(input, "partitions", true)?;
        let tagged_fields_callback = |tag: i32, _: &[u8]| {
            match tag {
                _ => Ok(false)
            }
        };
        let _unknown_tagged_fields = read_tagged_fields(input, tagged_fields_callback)?;
        Ok(TaskIds {
            subtopology_id, partitions, _unknown_tagged_fields
        })
    }
}

impl Writable for TaskIds {
    fn write(&self, #[allow(unused)] output: &mut impl Write) -> Result<()> {
        self.subtopology_id.write_ext(output, "self.subtopology_id", true)?;
        write_array(output, "self.partitions", &self.partitions, true)?;
        write_tagged_fields(output, &[], &self._unknown_tagged_fields)?;
        Ok(())
    }
}

/// TopicPartition, version 0.
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
#[cfg_attr(test, derive(Arbitrary))]
pub struct TopicPartition {
    /// topic name
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::string()"))]
    pub topic: String,
    /// partitions
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::vec()"))]
    pub partitions: Vec<i32>,
    /// Unknown tagged fields.
    #[cfg_attr(test, proptest(strategy = "proptest_strategies::unknown_tagged_fields()"))]
    pub _unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for TopicPartition {
    fn default() -> Self {
        TopicPartition {
            topic: String::from(""),
            partitions: Vec::<i32>::new(),
            _unknown_tagged_fields: Vec::new(),
        }
    }
}

impl TopicPartition {
    pub fn new<S1: AsRef<str>>(topic: S1, partitions: Vec<i32>) -> Self {
        Self {
            topic: topic.as_ref().to_string(),
            partitions,
            _unknown_tagged_fields: vec![],
        }
    }
}

#[cfg(test)]
mod tests_topic_partition_new_and_default {
    use super::*;
    
    #[test]
    fn test() {
        let d = TopicPartition::new(
            String::from(""),
            Vec::<i32>::new(),
        );
        assert_eq!(d, TopicPartition::default());
    }
}

impl Readable for TopicPartition {
    fn read(#[allow(unused)] input: &mut impl Read) -> Result<Self> {
        let topic = String::read_ext(input, "topic", true)?;
        let partitions = read_array::<i32>(input, "partitions", true)?;
        let tagged_fields_callback = |tag: i32, _: &[u8]| {
            match tag {
                _ => Ok(false)
            }
        };
        let _unknown_tagged_fields = read_tagged_fields(input, tagged_fields_callback)?;
        Ok(TopicPartition {
            topic, partitions, _unknown_tagged_fields
        })
    }
}

impl Writable for TopicPartition {
    fn write(&self, #[allow(unused)] output: &mut impl Write) -> Result<()> {
        self.topic.write_ext(output, "self.topic", true)?;
        write_array(output, "self.partitions", &self.partitions, true)?;
        write_tagged_fields(output, &[], &self._unknown_tagged_fields)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;
    
    #[test]
    fn test_java_default() {
        crate::test_utils::test_java_default::<StreamsGroupHeartbeatResponse>("StreamsGroupHeartbeatResponse", 0);
    }
    
    proptest! {
        #[test]
        fn test_serde(data: StreamsGroupHeartbeatResponse) {
            crate::test_utils::test_serde(&data)?;
        }
    }
    
    proptest! {
        #[test]
        fn test_java_arbitrary(data: StreamsGroupHeartbeatResponse) {
            crate::test_utils::test_java_arbitrary(&data, "StreamsGroupHeartbeatResponse", 0);
        }
    }
}
